extend = [
    { path = "Makefile.local.toml" },
    { path = "Makefile.ci.toml" },
    { path = "Makefile.contract.toml" },
]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[env]
FT_CONTRACT_ID = { value = "devswin.testnet", condition = { env_not_set = ["FT_CONTRACT_ID"] } }


[tasks.empty]
disabled = true
private = true

[tasks.init]
private = true

[tasks.end]
private = true