[tasks.cargo-test]
category = "LOCAL USAGE"
command = "cargo"
args = ["test", "--workspace", "--no-fail-fast"]

[tasks.cargo-fmt]
category = "LOCAL USAGE"
command = "cargo"
args = ["fmt", "--all"]

[tasks.cargo-check]
category = "LOCAL USAGE"
command = "cargo"
env = { RUSTFLAGS = "--cfg surrealdb_unstable" }
args = ["check", "--workspace"]

[tasks.cargo-clippy]
category = "LOCAL USAGE"
command = "cargo"
env = { RUSTFLAGS = "--cfg surrealdb_unstable" }
args = ["clippy", "--", "-D", "warnings"]


[tasks.cargo-doc]
category = "LOCAL USAGE"
command = "cargo"
args = ["doc", "--open", "--no-deps", "--all", "--target-dir", "./doc"]

[tasks.clean-doc]
category = "LOCAL USAGE"
command = "rm"
args = ["-rf", "./doc/debug", "./doc/.rustc_info.json", "./doc/.rustdoc_fingerprint.json"]

[tasks.cargo-clean]
category = "LOCAL USAGE"
command = "cargo"
args = ["clean"]

[tasks.build-contract]
category = "LOCAL USAGE"
cwd = "./contract"
command = "cargo"
args = ["near", "build", "--no-docker"]

[tasks.bc]
alias = "build-contract"

[tasks.deploy-contract]
category = "LOCAL USAGE"
cwd = "./contract"
script = "cargo near deploy $FT_CONTRACT_ID with-init-call new_default_meta json-args '{\"owner_id\": \"'$FT_CONTRACT_ID'\", \"total_supply\": \"0\"}' prepaid-gas '100.0 Tgas' attached-deposit '0 NEAR' network-config testnet sign-with-keychain send"

[tasks.dc]
alias = "dc"

[tasks.test]
category = "LOCAL USAGE"
dependencies = ["cargo-test"]

[tasks.check]
category = "LOCAL USAGE"
dependencies = ["cargo-check", "cargo-clippy"]

[tasks.clean]
category = "LOCAL USAGE"
dependencies = ["cargo-clean", "clean-doc"]

[tasks.default]
category = "LOCAL USAGE"
clear = true
dependencies = ["cargo-fmt", "check", "test"]